version: "3.5"

services:
  mongodb:
    image: mongo
    networks:
      - dev
    ports:
      - "27017:27017"

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb
    networks:
      - dev

  webserver:
    build: ./backend
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    networks:
      - dev
    environment:
     - MONGO_NAME=mongodb
     
networks:
  dev:
    name: dev
    driver: bridge